### ISSUE TITLE
Bundle install fails with "revealed dependencies not in the API"

### ISSUE THREAD

**Issue by chrisdavies** [pagodabox/nanobox-engine-ruby#32]
Here is the output when I try to launch my (existing) Rails application:

```
Downloading rack-protection-1.5.0 revealed dependencies not in the API or the
lockfile (rack (>= 0)).
Either installing with `--full-index` or running `bundle update rack-protection`
should fix the problem.
```

I can't figure out how to start the VM without it running `bundle install`, so that I can manually run these workarounds. Any ideas?

**Comment by danhunsaker** [comment]
This was mentioned on Slack, and you already tried it with success, but for future reference by other users, you can get into a debug console on failure by adding the `--debug` flag to your `nanobox build-runtime` or `nanobox run` command.
